name: Auto commit
on:
  push:
    branches:
      - master
  schedule:
    - cron: '30 1,2,3,4,5,6,7,8,9,10,11,23 * * *'
jobs:
  kang_commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Modify LAST_UPDATED file
        run: |
          d=`date '+%Y-%m-%dT%H:%M:%SZ'`
          echo $d > LAST_UPDATED
      - name: Commit changes
        run: |
          git config --local user.email "virusjalan86@gmail.com"
          git config --local user.name "Asuna Chan"
          git add -A
          arr[0]="quote: ğŸ˜‚ If you let your head get too big, itâ€™ll break your neck."
          arr[1]="quote: ğŸ˜± The road to success is dotted with many tempting parking spaces."
          arr[2]="quote: ğŸ‘¿ A diamond is merely a lump of coal that did well under pressure."
          arr[3]="quote: ğŸ’© Women who seek to be equal with men lack ambition."
          arr[4]="quote: ğŸ™ The best things in life are actually really expensive."
          arr[5]="quote: ğŸ™ˆ Bad decisions make good stories."
          arr[6]="quote: ğŸ Dreams are like rainbows. Only idiots chase them."
          arr[7]="quote: ğŸš€ If the world didnâ€™t suck weâ€™d all fly into space."
          arr[8]="quote: ğŸ•º Always remember that you are unique â€“ just like everybody else."
          arr[9]="quote: ğŸ“ People say nothing is impossible, but I do nothing every day."
          arr[10]="quote: ğŸ‘’ You canâ€™t have everything. Where would you put it?"
          rand=$[$RANDOM % ${#arr[@]}]
          git commit -m "${arr[$rand]}"
      - name: Push Back
        uses: ad-m/github-push-action@v0.5.0
        with:
          force: true
          directory: '.'
          github_token: ${{ secrets.GITHUB_TOKEN }}
